export const INIT_INGREDIENTS = 'INIT_INGREDIENTS';
export const INIT_INGREDIENTS_ERROR = 'INIT_INGREDIENTS_ERROR';
export const CHANGE_INGREDIENT = 'CHANGE_INGREDIENT';
export const RESET_INGREDIENTS = 'RESET_INGREDIENTS';
export const RANDOM_PIZZA = 'RANDOM_PIZZA';